"""First

Revision ID: a094f4e13bb8
Revises: 
Create Date: 2023-03-17 22:38:15.929753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a094f4e13bb8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_post',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(), nullable=True),
                    sa.Column('text', sa.String(length=350), nullable=True),
                    sa.Column('date', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blog_post_id'), 'blog_post', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blog_post_id'), table_name='blog_post')
    op.drop_table('blog_post')
    # ### end Alembic commands ###
